"""Pydantic models and JSON persistence for trading objectives and proposals."""

import json
import logging
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
OBJECTIVES_PATH = DATA_DIR / "trading_objectives.json"
PROPOSALS_PATH = DATA_DIR / "trade_proposals.json"


class RiskTolerance(str, Enum):
    LOW = "low"
    MODERATE = "moderate"
    AGGRESSIVE = "aggressive"


class ObjectiveStatus(str, Enum):
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"


class ProposalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTED = "executed"


class TradingObjective(BaseModel):
    """User-defined trading objective."""

    goal: str
    target_return_pct: float
    timeframe_days: int
    risk_tolerance: RiskTolerance = RiskTolerance.MODERATE
    max_position_pct: float = 30.0
    asset_universe: list[str] = Field(default_factory=list)
    max_daily_loss_pct: float = 2.0
    status: ObjectiveStatus = ObjectiveStatus.ACTIVE
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class TradeProposal(BaseModel):
    """A single trade proposal generated by the AI crew."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    symbol: str
    action: str
    qty: int
    rationale: str
    expected_impact: str
    risk_level: str
    risk_review: str = ""
    status: ProposalStatus = ProposalStatus.PENDING
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    reviewed_at: str | None = None


def _load_json(path: Path) -> Any:
    """Load a JSON file, returning None if missing or invalid."""
    if path.exists():
        try:
            return json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            logger.warning("Failed to read %s", path)
    return None


def _save_json(path: Path, data: Any) -> None:
    """Persist data to a JSON file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2))


def save_objective(obj: TradingObjective) -> dict[str, Any]:
    """Save the current trading objective (only one active at a time)."""
    obj.updated_at = datetime.now(timezone.utc).isoformat()
    data = obj.model_dump()
    _save_json(OBJECTIVES_PATH, data)
    return data


def load_objective() -> dict[str, Any] | None:
    """Load the current trading objective."""
    return _load_json(OBJECTIVES_PATH)


def save_proposal(proposal: TradeProposal) -> dict[str, Any]:
    """Append a proposal to the proposals list."""
    proposals = load_proposals()
    data = proposal.model_dump()
    proposals.append(data)
    _save_json(PROPOSALS_PATH, proposals)
    return data


def save_proposals_batch(proposals_list: list[TradeProposal]) -> list[dict[str, Any]]:
    """Save multiple proposals at once."""
    existing = load_proposals()
    new_data = [p.model_dump() for p in proposals_list]
    existing.extend(new_data)
    _save_json(PROPOSALS_PATH, existing)
    return new_data


def load_proposals(status: str | None = None) -> list[dict[str, Any]]:
    """Load all proposals, optionally filtered by status."""
    data = _load_json(PROPOSALS_PATH)
    if not isinstance(data, list):
        return []
    if status:
        return [p for p in data if p.get("status") == status]
    return data


def update_proposal_status(
    proposal_id: str, new_status: ProposalStatus
) -> dict[str, Any] | None:
    """Update a proposal's status by ID. Returns updated proposal or None."""
    proposals = load_proposals()
    for p in proposals:
        if p.get("id") == proposal_id:
            p["status"] = new_status.value
            if new_status in (ProposalStatus.APPROVED, ProposalStatus.REJECTED):
                p["reviewed_at"] = datetime.now(timezone.utc).isoformat()
            _save_json(PROPOSALS_PATH, proposals)
            return p
    return None
